$ProgressPreference = 'SilentlyContinue'
New-Item -ItemType Directory -Force -Path img | Out-Null
Write-Host "Downloading images to .\img ..."
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-1/Preview_Big.jpg' -OutFile 'img\p1_Preview_Big.jpg'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-1/Join_Mesh_Before.png' -OutFile 'img\Join_Mesh_Before.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-1/Limited_Dissolve.png' -OutFile 'img\Limited_Dissolve.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-1/Add_to_Collection.png' -OutFile 'img\Add_to_Collection.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-1/Textures_Overview.png' -OutFile 'img\Textures_Overview.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-1/UV_Project_from_View.png' -OutFile 'img\UV_Project_from_View.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-1/UV_Aligned_Texture.png' -OutFile 'img\UV_Aligned_Texture.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-2/Preview_Big.jpg' -OutFile 'img\p2_Preview_Big.jpg'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-2/Combine-Top-Bottom-Textures.png' -OutFile 'img\Combine-Top-Bottom-Textures.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-2/Texture-Group.png' -OutFile 'img\Texture-Group.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-2/Silkscreen-Material.png' -OutFile 'img\Silkscreen-Material.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-2/Soldermask-Material.png' -OutFile 'img\Soldermask-Material.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-2/Copper-Material.png' -OutFile 'img\Copper-Material.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-2/MiddleLayer-Material.png' -OutFile 'img\MiddleLayer-Material.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-2/Combine-Materials.png' -OutFile 'img\Combine-Materials.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-2/Middle-Decider.png' -OutFile 'img\Middle-Decider.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-2/Calculate-Displacement.png' -OutFile 'img\Calculate-Displacement.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-2/Final-Node-Setup.png' -OutFile 'img\Final-Node-Setup.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-3/Preview_Big.jpg' -OutFile 'img\p3_Preview_Big.jpg'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-3/Bevel_Node.png' -OutFile 'img\Bevel_Node.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-3/Unbeveled.png' -OutFile 'img\Unbeveled.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-3/Beveled.png' -OutFile 'img\Beveled.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-3/RAM_IC_UV.png' -OutFile 'img\RAM_IC_UV.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-3/RAM_IC_Material.png' -OutFile 'img\RAM_IC_Material.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-3/RAM_IC_Displacement.png' -OutFile 'img\RAM_IC_Displacement.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-3/Enable_Denoising_and_AO.png' -OutFile 'img\Enable_Denoising_and_AO.png'
Invoke-WebRequest -Uri 'https://static.blog.pcb-arts.com/blender-tutorial-3/Compositor_Denoising.png' -OutFile 'img\Compositor_Denoising.png'
Write-Host "Done."
